version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: postgres-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - APP_PORT=${APP_PORT}
    ports:
      - '3000:3000'
    container_name: nest-docker-postgres-todo-app
    depends_on:
      - db
    volumes:
      - .:/app
      - ./src:/app/src
      - /app/node_modules
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports:
      - '8080:80'
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
volumes:
  pgdata:
  pgadmin-data:
